### ISSUE TITLE
New objects get the subject as label

### ISSUE THREAD

**Issue by piekvossen** [leolani/cltl-knowledgerepresentation#33]
The utterance “I live in Weesp” results in the triple:
Triple in statement: piek_live-in_weesp [agent_->_person])
But in the brain we see:

“weesp" as a label for leolaniWorld:piek in addition to the label “piek”

The claim created is “piek_live-in_piek”

weesp is also in the brain with label “weesp” but n further properties

<img width="1623" alt="Screenshot 2022-10-31 at 09 01 33" src="https://user-images.githubusercontent.com/2635052/198960724-f8f8b69e-30dd-4c2b-a69c-8ff54d9ac912.png">
<img width="1601" alt="Screenshot 2022-10-31 at 09 01 05" src="https://user-images.githubusercontent.com/2635052/198960738-89500524-d651-4895-8475-e61f53722fd9.png">

**Comment by piekvossen** [comment]
I think I deduced that it is the KR when a triple is extracted. I started with a clean brain and the first screen dump is after G2KY and saying my name is Piek. The second screen dump of the brain is after typing directly after the naming, “I live in Weesp”.

<img width="1622" alt="Screenshot 2022-10-31 at 09 14 27" src="https://user-images.githubusercontent.com/2635052/198962512-d4f3615a-8f4f-4951-81ed-202e604a1661.png">
<img width="1628" alt="Screenshot 2022-10-31 at 09 15 14" src="https://user-images.githubusercontent.com/2635052/198962521-a166f837-b83e-4dce-b59f-5883407be9bb.png">

**Comment by numblr** [comment]
Seems to be an issue in the knowledge linking, here the capsule from the logs before and after linking:

cltl_service.entity_linking.service Linking capsule:
```
{
  'chat': '3f3e3ce0-8746-45e4-868c-8c2399986123',
  'turn': '31d4b304-829a-4d78-9e82-903076ab4b4f',
  'author': {
    'label': 'Piek',
    'type': [
      'person'
    ],
    'uri': 'http://cltl.nl/leolani/world/Piek'
  },
  'utterance': 'I am from Weesp',
  'utterance_type': <UtteranceType.STATEMENT
  :
  1>,
  'position': '0-15',
  'subject': {
    'label': 'Piek',
    'type': [
      'agent'
    ],
    'uri': None
  },
  'predicate': {
    'label': 'be-from',
    'type': [
      'stative'
    ],
    'uri': None
  },
  'object': {
    'label': 'Weesp',
    'type': [
      'person'
    ],
    'uri': None
  },
  'perspective': {
    'sentiment': 0.0,
    'certainty': 1.0,
    'polarity': 1.0,
    'emotion': 0.0
  },
  'context_id': None,
  'timestamp': 1667207263173
}
```

cltl_service.entity_linking.service Linked capsule:
```
{
  'chat': '3f3e3ce0-8746-45e4-868c-8c2399986123',
  'turn': '31d4b304-829a-4d78-9e82-903076ab4b4f',
  'author': {
    'label': 'Piek',
    'type': [
      'person'
    ],
    'uri': 'http://cltl.nl/leolani/world/Piek'
  },
  'utterance': 'I am from Weesp',
  'utterance_type': <UtteranceType.STATEMENT
  :
  1>,
  'position': '0-15',
  'subject': {
    'label': 'Piek',
    'type': [
      'agent'
    ],
    'uri': 'http://cltl.nl/leolani/world/piek'
  },
  'predicate': {
    'label': 'be-from',
    'type': [
      'stative'
    ],
    'uri': 'http://cltl.nl/leolani/n2mu/be-from'
  },
  'object': {
    'label': 'Weesp',
    'type': [
      'person'
    ],
    'uri': 'http://cltl.nl/leolani/world/Piek'
  },
  'perspective': {
    'sentiment': 0.0,
    'certainty': 1.0,
    'polarity': 1.0,
    'emotion': 0.0
  },
  'context_id': None,
  'timestamp': 1667207263173
}
```

**Comment by piekvossen** [comment]
Resolved in knowledge extraction by assigning the None type to objects with capitals instead of person.
